"""Add User and Referral models

Revision ID: 250688403409
Revises: 006_tree_deltas
Create Date: 2026-08-10 20:37:25.935669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '250688403409'
down_revision: Union[str, None] = '006_tree_deltas'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referring_providers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('npi', sa.String(length=50), nullable=True),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('practice_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('fax', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('npi')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'surgeon', 'patient', name='user_role_enum'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('specialist_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('referral_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_knowledge_chunks_embedding'), table_name='knowledge_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('ix_knowledge_chunks_tree_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    
    # Create ENUMs for referrals
    sa.Enum('epic', 'fax', 'phone', 'other', name='referral_channel_enum').create(op.get_bind())
    sa.Enum('routine', 'urgent', name='referral_priority_enum').create(op.get_bind())
    sa.Enum('new', 'needs_review', 'reviewed', 'scheduled', 'dismissed', name='referral_status_enum').create(op.get_bind())

    op.add_column('patients', sa.Column('sex', sa.String(length=10), nullable=True))
    op.add_column('referrals', sa.Column('display_id', sa.String(length=50), nullable=False))
    op.add_column('referrals', sa.Column('referred_by_id', sa.String(length=36), nullable=True))
    op.add_column('referrals', sa.Column('routed_specialist_id', sa.String(length=36), nullable=True))
    op.add_column('referrals', sa.Column('tree_id', sa.String(length=36), nullable=True))
    op.add_column('referrals', sa.Column('received_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('referrals', sa.Column('channel', sa.Enum('epic', 'fax', 'phone', 'other', name='referral_channel_enum'), nullable=False))
    op.add_column('referrals', sa.Column('priority', sa.Enum('routine', 'urgent', name='referral_priority_enum'), nullable=False))
    op.add_column('referrals', sa.Column('reason_for_referral', sa.Text(), nullable=True))
    op.add_column('referrals', sa.Column('clinical_note', sa.Text(), nullable=True))
    op.add_column('referrals', sa.Column('extraction', sa.JSON(), nullable=True))
    op.add_column('referrals', sa.Column('annotations', sa.JSON(), nullable=True))
    op.add_column('referrals', sa.Column('structured_data', sa.JSON(), nullable=True))
    op.alter_column('referrals', 'patient_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.execute('ALTER TABLE referrals ALTER COLUMN status DROP DEFAULT')
    op.execute('ALTER TABLE referrals ALTER COLUMN status TYPE referral_status_enum USING status::text::referral_status_enum')
    op.drop_index(op.f('ix_referrals_patient_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_status'), table_name='referrals')
    op.drop_constraint(op.f('referrals_conversation_id_key'), 'referrals', type_='unique')
    op.create_unique_constraint(None, 'referrals', ['display_id'])
    op.drop_constraint(op.f('referrals_conversation_id_fkey'), 'referrals', type_='foreignkey')
    op.create_foreign_key(None, 'referrals', 'trees', ['tree_id'], ['id'])
    op.create_foreign_key(None, 'referrals', 'referring_providers', ['referred_by_id'], ['id'])
    op.create_foreign_key(None, 'referrals', 'specialists', ['routed_specialist_id'], ['id'])
    op.drop_column('referrals', 'document_url')
    op.drop_column('referrals', 'sections_json')
    op.drop_column('referrals', 'conversation_id')
    op.drop_column('referrals', 'epic_patient_fhir_id')
    op.drop_column('referrals', 'extraction_json')
    op.drop_column('referrals', 'ccda_raw')
    op.drop_column('referrals', 'extraction_summary')
    op.drop_column('referrals', 'document_reference_id')
    op.drop_column('variables', 'clinical_mappings')
    op.drop_column('variables', 'patient_examples')
    op.drop_column('variables', 'synonyms')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variables', sa.Column('synonyms', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('variables', sa.Column('patient_examples', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('variables', sa.Column('clinical_mappings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('referrals', sa.Column('document_reference_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('referrals', sa.Column('extraction_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('referrals', sa.Column('ccda_raw', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('referrals', sa.Column('extraction_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('referrals', sa.Column('epic_patient_fhir_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('referrals', sa.Column('conversation_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.add_column('referrals', sa.Column('sections_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('referrals', sa.Column('document_url', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.create_foreign_key(op.f('referrals_conversation_id_fkey'), 'referrals', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'referrals', type_='unique')
    op.create_unique_constraint(op.f('referrals_conversation_id_key'), 'referrals', ['conversation_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_referrals_status'), 'referrals', ['status'], unique=False)
    op.create_index(op.f('ix_referrals_patient_id'), 'referrals', ['patient_id'], unique=False)
    op.alter_column('referrals', 'status',
               existing_type=sa.Enum('new', 'needs_review', 'reviewed', 'scheduled', 'dismissed', name='referral_status_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('referrals', 'patient_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('referrals', 'structured_data')
    op.drop_column('referrals', 'annotations')
    op.drop_column('referrals', 'extraction')
    op.drop_column('referrals', 'clinical_note')
    op.drop_column('referrals', 'reason_for_referral')
    op.drop_column('referrals', 'priority')
    op.drop_column('referrals', 'channel')
    op.drop_column('referrals', 'received_at')
    op.drop_column('referrals', 'tree_id')
    op.drop_column('referrals', 'routed_specialist_id')
    op.drop_column('referrals', 'referred_by_id')
    op.drop_column('referrals', 'display_id')
    op.drop_column('patients', 'sex')
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('tree_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('clinic_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('matched_terms', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('embedding', sa.NullType(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], name=op.f('knowledge_chunks_clinic_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], name=op.f('knowledge_chunks_tree_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('knowledge_chunks_pkey'))
    )
    op.create_index(op.f('ix_knowledge_chunks_tree_id'), 'knowledge_chunks', ['tree_id'], unique=False)
    op.create_index(op.f('ix_knowledge_chunks_embedding'), 'knowledge_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_table('attachments')
    op.drop_table('users')
    op.drop_table('referring_providers')
    # ### end Alembic commands ###
