"""create_tables

Revision ID: 775fa6e95917
Revises: 001_initial
Create Date: 2026-06-25 02:43:04.368164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '775fa6e95917'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('knowledge_base', sa.Text(), nullable=True),
    sa.Column('group', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('variables',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('clinical_prompt', sa.Text(), nullable=True),
    sa.Column('patient_question', sa.Text(), nullable=True),
    sa.Column('answer_type', sa.Enum('single_choice', 'number', 'boolean', 'text', name='answer_type_enum'), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=True),
    sa.Column('extraction_hints', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('patients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clinic_id', sa.String(length=36), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('mrn', sa.String(length=100), nullable=True),
    sa.Column('referring_provider', sa.String(length=255), nullable=True),
    sa.Column('referral_date', sa.Date(), nullable=True),
    sa.Column('referral_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mrn')
    )
    op.create_table('specialists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('clinic_id', sa.String(length=36), nullable=True),
    sa.Column('specialty', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('clinic_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('root_node_id', sa.String(length=36), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('authored_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=True),
    sa.Column('tree_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('in_progress', 'routed', 'escalated', 'abandoned', name='conversation_status_enum'), nullable=False),
    sa.Column('outcome_specialist_id', sa.String(length=36), nullable=True),
    sa.Column('outcome_urgency', sa.Enum('routine', 'expedited', 'urgent', name='outcome_urgency_enum'), nullable=True),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('path_taken', sa.JSON(), nullable=True),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('questions_asked', sa.Integer(), nullable=False),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['outcome_specialist_id'], ['specialists.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tree_id', sa.String(length=36), nullable=False),
    sa.Column('node_type', sa.Enum('variable', 'specialist', 'escalation', name='node_type_enum'), nullable=False),
    sa.Column('variable_key', sa.String(length=100), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('data_source', sa.Enum('patient', 'referral', 'record', name='data_source_enum'), nullable=True),
    sa.Column('specialist_name', sa.String(length=255), nullable=True),
    sa.Column('specialty', sa.String(length=255), nullable=True),
    sa.Column('urgency', sa.Enum('routine', 'expedited', 'urgent', name='urgency_enum'), nullable=True),
    sa.Column('reasoning_template', sa.Text(), nullable=True),
    sa.Column('clinical_basis', sa.Text(), nullable=True),
    sa.Column('confirm_with_dr_li', sa.Boolean(), nullable=True),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tree_id'], ['trees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'tree_id')
    )
    op.create_table('patient_clinics',
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('clinic_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('patient_id', 'clinic_id')
    )
    op.create_table('actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('tree_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('patient_label', sa.String(length=500), nullable=True),
    sa.Column('next_node_id', sa.String(length=36), nullable=True),
    sa.Column('branch_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id', 'tree_id'], ['nodes.id', 'nodes.tree_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversation_turns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('patient', 'assistant', name='turn_role_enum'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('node_id', sa.String(length=36), nullable=True),
    sa.Column('variable_key', sa.String(length=100), nullable=True),
    sa.Column('is_confirmation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_variables',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('variable_key', sa.String(length=100), nullable=False),
    sa.Column('value_string', sa.Text(), nullable=True),
    sa.Column('value_number', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('via', sa.Enum('extraction', 'answer', 'confirmation', name='variable_via_enum'), nullable=False),
    sa.Column('reason_for_clarification', sa.String(length=500), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variable_key'], ['variables.key'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workup_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('tree_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('protocol', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('item_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['node_id', 'tree_id'], ['nodes.id', 'nodes.tree_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conditions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('branch_id', sa.String(length=36), nullable=False),
    sa.Column('condition_type', sa.Enum('equals', 'range', 'in', name='condition_type_enum'), nullable=False),
    sa.Column('value_string', sa.String(length=500), nullable=True),
    sa.Column('values_list', sa.Text(), nullable=True),
    sa.Column('min_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_value', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conditions')
    op.drop_table('workup_items')
    op.drop_table('patient_variables')
    op.drop_table('conversation_turns')
    op.drop_table('branches')
    op.drop_table('actions')
    op.drop_table('patient_clinics')
    op.drop_table('nodes')
    op.drop_table('conversations')
    op.drop_table('trees')
    op.drop_table('specialists')
    op.drop_table('patients')
    op.drop_table('variables')
    op.drop_table('clinics')
    # ### end Alembic commands ###
