"""Add referral_id to Conversation

Revision ID: f211f5855867
Revises: 008_audit_log
Create Date: 2026-08-11 15:42:25.725924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f211f5855867'
down_revision: Union[str, None] = '008_audit_log'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_clinic_active_tree'), 'clinics', type_='foreignkey')
    op.create_foreign_key('fk_clinic_active_tree', 'clinics', 'trees', ['active_tree_id'], ['id'], use_alter=True)
    op.add_column('conversations', sa.Column('referral_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'conversations', 'referrals', ['referral_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_column('conversations', 'referral_id')
    op.drop_constraint('fk_clinic_active_tree', 'clinics', type_='foreignkey')
    op.create_foreign_key(op.f('fk_clinic_active_tree'), 'clinics', 'trees', ['active_tree_id'], ['id'], ondelete='SET NULL', initially='DEFERRED', deferrable=True)
    # ### end Alembic commands ###
